### ISSUE TITLE
How to open the file browser

### ISSUE THREAD

**Issue by bleutzinn** [N-Parsons/grav-plugin-file-browser#1]
It must be something I overlooked or simply do not grasp, but how should a visitor open the file browser?

**Comment by N-Parsons** [comment]
Sorry for taking a while to get back to you. Seemingly I wasn't set as a watcher for this repo, so I didn't get a notification!

For some reason, I forgot to explain how to use it in the README, so I will update that now to avoid future confusion!

To use the plugin, you need to create a page that uses the `file_browser_plugin.html.twig` template (named "File browser plugin" in the Admin panel). The user will then see the file browser embedded in that page when they navigate to it.
