### ISSUE TITLE
Get Forbidden when trying to access files

### ISSUE THREAD

**Issue by 0uro** [N-Parsons/grav-plugin-file-browser#16]
Hello,

I've built latest docker Grav image, and installed your file browser plugin using grav admin GUI.
I'm not doing anything fancy, just want to create a very simple website with some files.

But when I click on a file in /var/www/html/user/files I keep getting that error : You don't have permission to access this resource
Permissions are fine : www-data and 755

Besides, the navigation icons are missing. Could that be related ?

Thank you for your work

**Comment by N-Parsons** [comment]
Missing navigation icons is a separate issue - it means that you haven't loaded Font Awesome. You can either do this manually, or enable "Load Font Awesome v5 Free" in the plugin configuration in Admin, or set `load_font_awesome: true` in the plugin configuration file.

I haven't used the Docker image, so I'm not familiar with the configuration. I can set one up and poke around, but it would be useful to have some more detail first. Could you let me know what docker command or docker-compose file you used? Additionally, is the error specifically when you try to open a file (ie. does the plugin display the files correctly)?

**Comment by 0uro** [comment]
Arrows : fixed, thanks 

Yes files are correctly displayed

Here are the steps : 
1. docker build -t grav:latest
2. docker run -d -p 80:80 --name grav --restart always -v grav_data:/var/www/html grav:latest (no signifcant changes from original command)
3. installation & configuration of file-manager plugin
4. create page /home/files , select file-manager template
5. create folder (inside docker path : /var/www/html/user/files)
6. put some dummy files inside (readme.txt)
7. fix perms : chown -R www-data:www-data and chmod -R 755 on /var/lib/docker/volumes/grav_data/ (double checked perms from inside the container too)
8. navigate to page fr/home/files , click on file and I get 403 forbidden

I noticed something : when browsing, on the browser I have <website>/fr/home/files/readme.txt, and the file points to <website>/user/files/readme.txt. I tried changing the URI to <website>/fr/user/files/readme.txt but it gives a 404 error. Don't know if it's relevant.

**Comment by N-Parsons** [comment]
Thanks. That sounds like an issue with the web server configuration rather than this plugin. I took a look at my Nginx config (which is pretty much standard) and it forbids access to `.txt` and other files in the `/user` folder for security reasons, so I presume that the Apache configuration in the container is doing the same.

I'll take a look later and try to find a suitable configuration for removing these restrictions on the `/user/files` folder without hurting the security of the rest of the system. I definitely think it would be worth documenting within this repo.

**Comment by N-Parsons** [comment]
I've now documented the necessary server configuration changes in README.md.

---

## Server configuration

Grav's default webserver configurations block access to specific file types for security reasons - you don't want people to be able to access arbitrary and potentially sensitive files!
Therefore, if you want users to be able to access these file types, you will need to update your webserver configuration.

### Apache

Open `.htaccess` in your grav root directory and find these line:

```apache
# Block access to specific file types for these user folders
RewriteRule ^(user)/(.*)\.(txt|md|yaml|yml|php|pl|py|cgi|twig|sh|bat)$ error [F]
# Block all direct access to .md files:
RewriteRule \.md$ error [F]
```

To enable access to files in your `files` folder, update the line as follows. The second rule is optional, but improves security by continuing to block access to scripts in your `user/files` folder. 

```apache
# Block access to specific file types for these user folders
RewriteRule ^(user)/((?!files).*)\.(txt|md|yaml|yml|php|pl|py|cgi|twig|sh|bat)$ error [F]

# Block access to scripts in the user/files folder
RewriteRule ^(user)/(files)/.*\.(php|pl|py|cgi|twig|sh|bat)$ error [F]

# Block access to all .md files, except in user/files
RewriteRule ^(?!user/files/).*\.md$ error [F]
```


### Nginx

Open your nginx configuration file and find this line:

```nginx
# deny running scripts inside user folder
location ~* /user/.*\.(txt|md|yaml|yml|php|pl|py|cgi|twig|sh|bat)$ { return 403; }
```

To enable access to files in your `files` folder, update the line as follows. The second rule is optional, but improves security by continuing to block access to scripts in your `user/files` folder.

```nginx
# deny running scripts inside user folder
location ~* /user/(?!files).*\.(txt|md|yaml|yml|php|pl|py|cgi|twig|sh|bat)$ { return 403; }

# block access to scripts in the user/files folder
location ~* /user/files/.*\.(php|pl|py|cgi|twig|sh|bat)$ { return 403; }
```
