### ISSUE TITLE
Linked documents generate 404

### ISSUE THREAD

**Issue by awrog** [N-Parsons/grav-plugin-file-browser#5]
Fist of all, a great plugin, I love it!!
I implemented it and it works beautifully.
There is a tiny problem that the selected document generates an 404.
In this case, the location of the page is inserted in the URL:
http://kerst035.nl/grav/vve-lid/documenten/user/files/liften.jpg  ->
http://kerst035.nl/grav/user/files/liften.jpg

see animation
![error-file-browser](https://user-images.githubusercontent.com/12153667/63081508-130fe180-bf44-11e9-8626-760c1fe42274.gif)

**Comment by N-Parsons** [comment]
Thanks for the bug report. I can confirm that this is also happening for me!

**Comment by N-Parsons** [comment]
@awrog, thanks for the detailed bug report! I've fixed the issue and created a new release (v0.2.3), so it should become available via the GPM in the next few hours.

I've also added handling for Grav being hosted in a subdirectory (as you appear to have), so hopefully it should work properly for you now, but please let me know if it doesn't.
